server:
  contextPath: /java/summer/spring-data-rest-jpa
  port: 8080

management:
  context-path: /_manage


spring:
  jpa:
    hibernate:
      ddl-auto: update


h2:
  database:
      username: sa
      password: sa
      jdbc-url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
      min-pool-size: 1
      max-pool-size: 10
      initial-pool-size: 1
      acquire-increment: 2
      idle-test-period: 100
      max-statements: 100
      checkout-timeout: 30000
      driverClassName: org.h2.Driver
